### ISSUE TITLE
Cannot delete segments in mapped measurements

### ISSUE THREAD

**Issue by Matt-Power** [Bruker-Amics/bugs_features#306]
v3.3.0.1315
It is no longer possible to delete segments (pixel points) in mapped measurements.

**Comment by MarkGuo7** [comment]
Hi Matt

Could you show me how to repeat this issue? Seems I still can delete them. 

![image.png](https://images.zenhubusercontent.com/60a59e61f0254ad3e154481a/eecc2576-ae7f-4e89-b952-ca97b403c859)

**Comment by Matt-Power** [comment]
Hmmm. All of my mapped measurements are like this so you should see it straight away - are you sure that the big red delete "X" is still available?

To recreate, just select the mapped segments / points (this all works fine) but at no point does the delete button become available. Behaviour is shown below - segements are selected but no ability to delete (button is still greyed out).

![image](https://user-images.githubusercontent.com/84986921/200368692-89c9a7ff-f58d-4546-abc6-31ab56bf5d7b.png)

**Comment by MarkGuo7** [comment]
Hi @Matt-Power 

Not sure it is issue with the version you have. Seems from my side is normal.
Is it Ok to the latest installer?
Or let me know which version you are on, so I can take a look of your version.

**Comment by Matt-Power** [comment]
I'm still on 3.3.0.1315 (not updated yet, sorry) - will give the new version a go.

**Comment by MarkGuo7** [comment]
Let me try your version first.

**Comment by Matt-Power** [comment]
Still there in v3.3.0.1399 I'm afraid. You can try those mapped measurements that I sent - it doesn't work on those (at least not on my computer).

**Comment by MarkGuo7** [comment]
Sorry Matt

Did you see this message after opening mapping results?
The reason of couldn't delete is that the result is converted one. 
We shouldn't convert automatically every time. Currently I am working on Mapping related issues and this one has been fixed from the build I uploaded yesterday. 1406.
Please give it a try and let me know if it still there.

![image](https://user-images.githubusercontent.com/84481724/200451918-b8917dd9-d57d-4a1d-883b-b06500a8f40e.png)

**Comment by Matt-Power** [comment]
Hi Mark,

Yes I did see the message - I did assume that was something to do with issue (and the batch process issue #295). Is there a way to switch off the automatic conversion?
Once the little issues are ironed, out, I think that the automatic conversion will be very useful though. 

Will download the new version and give it a go.

Cheers,

Matt

**Comment by MarkGuo7** [comment]
Thanks Matt

I think you are right. I am working on Mapping mode results now.
Will take care of this issue.

Mark

**Comment by GGloy** [comment]
@MarkGuo7 this is still an issue in vs1501 - once you convert the sample the delete button is disabled.

**Comment by MarkGuo7** [comment]
Thanks Gerda, I will take a look.
Please kindly share your datastore as you showed me this morning.
@GGloy

**Comment by GGloy** [comment]
@MarkGuo7 just a reminder of this issue- it is still there in vs1508

**Comment by ChiLyMan** [comment]
Just tried this on v1508 on a Matrix Mapping dataset. The automatic convert does not seem to be there anymore and can delete pixels (segments).
https://images.zenhubusercontent.com/368966218/e0a71b4c-3936-4694-a6a6-bd86e06df92c/matrix_mapping_delete.mp4
